#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    yAmtr,          sensorAccelerometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SAMPLE_SIZE

float //xAccel[SAMPLE_SIZE],
	yAccel[SAMPLE_SIZE],
	deltaTheta[SAMPLE_SIZE],
	//xAccelAvg = 0,
	yAccelAvg = 0,
	deltaThetaAvg = 0,
	thetaLast = 0,
	//xVel = 0,
	yVel = 0,
	xPos = 0,
	yPos = 0;
const float thetaThresh = 10;

task main()
{
	for(int i = 0; i < SAMPLE_SIZE; i++) {
		//xAccel[i] = 0;
		yAccel[i] = 0;
		deltaTheta[i] = 0;
	}
	while(true) {
		for(int i = SAMPLE_SIZE - 1; i > 0; i--) {
			//xAccel[i] = xAccel[i-1];
			yAccel[i] = yAccel[i-1];
			deltaTheta[i] = deltaTheta[i-1];
		}

		//xAccel[0] = SensorValue[xAmtr];
		yAccel[0] = SensorValue[yAmtr];
		deltaTheta[0] = SensorValue[gyro] - thetaLast;
		thetaLast = SensorValue[gyro];
		if(abs(deltaTheta[0]) < thetaThresh)
			deltaTheta[0] = 0;

		//xAccelAvg =
			yAccelAvg =
			deltaThetaAvg =
			0;

		for(int a = 0; a < SAMPLE_SIZE; a++) {
			//xAccelAvg += xAccel[a];
			yAccelAvg += yAccel[a];
			deltaThetaAvg += deltaTheta[a];
		}

		//xAccelAvg /= SAMPLE_SIZE;
		yAccelAvg = yAccelAvg / SAMPLE_SIZE;
		deltaThetaAvg = deltaThetaAvg / SAMPLE_SIZE;

		//xVel += xAccelAvg;
		yVel += yAccelAvg;
		theta += deltaThetaAvg;

		xPos += sin(theta) * yVel;
		yPos += cos(theta) * yVel;

	}
}
